[[redirects]]
from = "/images/*"
to = "https://res.cloudinary.com/inl/image/fetch/f_auto,q_auto/https://indiannationalleague.netlify.app/cld-assets/images/:splat?_a=BBFAAAAA0"
status = 302
force = true

[[redirects]]
from = "/cld-assets/images/*"
to = "/images/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context]

  [context.production]

  [context.main]